---
title: "About"
format:
  html:
    code-links:
      - text: site repository
        href: https://www.github.com/calv2n/calv2n.github.io
        icon: github
---

The most recent copy of my **resume** [can be found here.](https://drive.google.com/file/d/18m9deW-zvAJwQ32xp2XWKmBaR3QZ3U9W/view?usp=sharing)

Calvin Carter is a passionate Data Scientist with extensive project experience using Python, R, and PostgreSQL. His current career goal is an internship in Data Science or Data Analytics while he completes his Masters degree in Statistics at UC Berkeley.

## More About Me

In my free time, I enjoy learning about world history & geography, hanging out with friends and family, and listening to & collecting music by the album (my favorite genres are Hip-Hop, R&B, Art Pop, and Alternative Rock). I also occasionally enjoy DIY projects, especially if they're software/computer-based.

Some fun facts about me:

- I've wanted to be a Data Scientist ever since I took Statistics in my junior year of high school, even though I only signed up for the class to be among friends. Who knew!

- I was a 3rd year transfer to UC Berkeley (from Cosumnes River College in Sacramento).

- I lived in New Mexico from ages 4-14 years old, then I moved to Northern California.

- I wasn't able to whistle until last year.
